version: '3'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
    working_dir: /home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    user: "1000:0"
    environment:
      - LOAD_EXAMPLES=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=abcd1234efgh5678
      - JUPYTER_DATA_PATH=/home/jovyan/work
    volumes:
      - /home/jovyan/work:/home/jovyan/work
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - postgres

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    user: "1000:0"
    environment:
      - LOAD_EXAMPLES=False
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=abcd1234efgh5678
      - JUPYTER_DATA_PATH=/home/jovyan/work
    volumes:
      - /home/jovyan/work:/home/jovyan/work
    command: scheduler
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.7.1
    ports:
      - "5000:5000"
    volumes:
      - /home/jovyan/work:/home/jovyan/work
    command: ["mlflow", "server", "--backend-store-uri", "/home/jovyan/work/mlruns", "--default-artifact-root", "/home/jovyan/work/mlruns", "--host", "0.0.0.0", "--port", "5000"]


volumes:
  postgres_data:
  logs:
  config:
  datasets:
  libs:
  mlruns:
  outputs:
  plots:
