model_name: 'dummy_data'
model_artifact_name: 'TSMixerModel3'
experiment_version: '1.1'
production_version: '1.1'
features:
  - "linear"
  - "exponential"
  - "sinusoidal"
  # - "short"
  # - "short2"
csv_paths:
  - "datasets/dummy_linear_distinct.csv"
  - "datasets/dummy_exponential_distinct.csv"
  - "datasets/dummy_sinusoidal_distinct.csv"
  # - "datasets/dummy_zero_series.csv"
  # - "datasets/dummy_zero_series2.csv"
register_experiment: False
register_model: False
train_size: 0.8
epochs: 50
batch_size: 8
patience: 5
look_back: 10
stage: "Production"  # or "Staging"
